apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cutlink.fullname" . }}-backend
  namespace: {{ include "cutlink.namespace" . }}
  labels:
    {{- include "cutlink.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "cutlink.db.host" . | quote }}
  DB_NAME: {{ .Values.backend.env.DB_NAME | quote }}
  DB_USER: {{ .Values.backend.env.DB_USER | quote }}
  BASE_URL: {{ .Values.backend.env.BASE_URL | quote }}
  REDIS_HOST: {{ include "cutlink.redis.host" . | quote }}
