apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: billflow-staging
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: billflow
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: staging
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
commonLabels:
  environment: staging
