apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: billflow-dev
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: billflow
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: dev
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi
commonLabels:
  environment: dev
