# -----------------------------------------------------------------------------
# Root Terragrunt Configuration — FinStack
#
# This is the root terragrunt.hcl that all environment configs inherit from.
# It configures:
#   1. Remote state in S3 with DynamoDB locking
#   2. AWS provider generation (so modules don't repeat provider blocks)
#   3. Common input variables shared across all environments
#
# Environment-specific configs in environments/<env>/terragrunt.hcl override
# the locals below (region, account_id, environment name).
# -----------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Remote state — S3 backend with DynamoDB locking
# ---------------------------------------------------------------------------

remote_state {
  backend = "s3"

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    bucket         = "finstack-terraform-state-${local.account_id}"
    key            = "${local.environment}/${path_relative_to_include()}/terraform.tfstate"
    region         = local.aws_region
    encrypt        = true                                          # SSE-S3 encryption at rest
    dynamodb_table = "finstack-terraform-locks"                    # state locking
    s3_bucket_tags = local.common_tags
  }
}

# ---------------------------------------------------------------------------
# Provider generation — every child module gets an AWS provider automatically
# ---------------------------------------------------------------------------

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"

  contents = <<-EOF
    # Auto-generated by Terragrunt — do not edit manually
    provider "aws" {
      region = "${local.aws_region}"

      default_tags {
        tags = {
          Project     = "finstack"
          Environment = "${local.environment}"
          ManagedBy   = "terragrunt"
          CostCentre  = "payments-platform"
        }
      }
    }
  EOF
}

# ---------------------------------------------------------------------------
# Common locals — overridden per environment
# ---------------------------------------------------------------------------

locals {
  # Defaults — environment-specific terragrunt.hcl files override these
  aws_region  = "ap-south-1"
  account_id  = get_env("AWS_ACCOUNT_ID", "123456789012")   # placeholder for LocalStack
  environment = "dev"                                         # overridden by child configs
  project     = "finstack"

  common_tags = {
    Project     = local.project
    Environment = local.environment
    ManagedBy   = "terragrunt"
    CostCentre  = "payments-platform"
    Compliance  = "rbi-pci-dss"                              # BFSI regulatory tag
  }
}

# ---------------------------------------------------------------------------
# Common inputs passed to every Terraform module
# ---------------------------------------------------------------------------

inputs = {
  project      = local.project
  environment  = local.environment
  aws_region   = local.aws_region
  tags         = local.common_tags
}
